Create react app
Inkvizi/admin-panel pull request #3
Opened 2021-05-09 09:07 UTC by Inkvizi

Создано приложение и выполнена верстка страницы

2021-05-11 07:55 UTC, Muslik commented on src/components/ChangeStatusButton/ChangeStatusButton.js
> +import styles from './ChangeStatusButton.module.css';
Если файл содержит jsx разметку, то расширение у файла нужно указать 'jsx'

2021-05-11 08:21 UTC, Muslik requested changes

2021-05-11 08:21 UTC, Muslik commented on src/components/CheckBox/CheckBox.module.css
> +    flex-direction: row;
flex-direction: row - по умолчанию стоит. Не нужно указывать

2021-05-11 08:21 UTC, Muslik commented on src/components/ChangeStatusButton/ChangeStatusButton.js
> +export function ChangeStatusButton(props) {
Если файл содержит jsx разметку, то принято использовать расширение .jsx

2021-05-11 08:21 UTC, Muslik commented on src/components/CheckBox/CheckBox.js
> +export function CheckBox(props) {
Тут можно деструктуризацию применить и сразу будет видно какие свойства приходят.
export function Checkbox({ id, value })

2021-05-11 08:21 UTC, Muslik commented on src/components/CheckBox/CheckBox.js
> +            <label className={styles.checkboxLabel} for={props.id}>
У label нету тега for, только htmlFor.
Если input внутри label, то не нужно указывать связку htmlFor + id

2021-05-11 08:21 UTC, Muslik commented on src/components/CheckBox/CheckBox.module.css
>          --b: var(--disabled);
Что значит переменная --b. Переменные должны быть понятнями

2021-05-11 08:21 UTC, Muslik commented on src/components/FilterBodyPanel/FilterBodyPanel.js
> +            <FilterApplyButton></FilterApplyButton>
Если внутри тега нету ничего, то можно указать проще: <FilterApplyButton />

2021-05-11 08:21 UTC, Muslik commented on src/components/FilterSelect/FilterSelect.js
> +            checkBoxesRef.current.style.display = "flex";
Почитайте про библиотеку classNames. Она позволят применять какой то класс в зависимости от условия. ref не очень красиво выглядит для применения стилей. И тогда функция будет выглядеть намного проще. 
`
 const showCheckboxes = ({ target: { checked }}) => {
        setExpanded(!checked);
    }
`

2021-05-11 08:21 UTC, Muslik commented on src/components/Page/Page.js
> +    const tableData = [
Можно вынести данные из компонента и положить в файл с константами

2021-05-11 08:21 UTC, Muslik commented on src/components/Table/Table.js
> +    const data = props.data.map(order =>
У каждого элемента в map должен быть key - https://reactjs.org/docs/lists-and-keys.html

2021-05-11 08:21 UTC, Muslik commented on src/components/Table/Table.js
> +            <td className={styles.td}>{(order.status === "Отменен")?'\u2014':order.itemsCount}</td>
Отменен в константы.
`export const CANCELED = 'Отменен';`

order.status === CANCELED

2021-05-11 13:36 UTC, Inkvizi commented on src/components/CheckBox/CheckBox.module.css
> +    flex-direction: row;
удалил

2021-05-11 13:50 UTC, Inkvizi commented on src/components/ChangeStatusButton/ChangeStatusButton.js
> +export function ChangeStatusButton(props) {
переименовал

2021-05-11 14:04 UTC, Inkvizi commented on src/components/CheckBox/CheckBox.module.css
>          --b: var(--disabled);
переназвал

2021-05-11 14:05 UTC, Inkvizi commented on src/components/FilterBodyPanel/FilterBodyPanel.js
> +            <FilterApplyButton></FilterApplyButton>
Указал

2021-05-11 14:17 UTC, Inkvizi commented on src/components/Page/Page.js
> +    const tableData = [
перенес

2021-05-11 14:23 UTC, Inkvizi commented on src/components/Table/Table.js
> +    const data = props.data.map(order =>
добавил

2021-05-11 14:25 UTC, Inkvizi commented on src/components/Table/Table.js
> +            <td className={styles.td}>{(order.status === "Отменен")?'\u2014':order.itemsCount}</td>
Перенес

2021-05-11 18:16 UTC, Inkvizi commented on src/components/FilterSelect/FilterSelect.js
> +            checkBoxesRef.current.style.display = "flex";
Переделал

2021-05-11 19:56 UTC, Muslik requested changes

2021-05-11 19:56 UTC, Muslik commented on src/components/CheckBox/CheckBox.jsx
> +                <input type="checkbox" className={styles.checkBox} id = {id}/>
id={id} не нужно пробела. Но тут скорее prettier должен быть установлен чтобы все автоматом выравнивалось. Есть два невероятно полезных инструмента:
https://eslint.org/ - показывает ошибки чтобы поддерживать код в едином стиле.
https://prettier.io/ - занимается автоматическим форматированием кода.
Сейчас когда вы работаете один, это может и  не имеет значения, но если над проектом трудится команда, то эти инструменты незаменимы. Да даже в случае сольного проекта бывает круто когда все написано одинаково.
Советую вам ознакомиться на досуге

2021-05-11 19:56 UTC, Muslik commented on src/components/FilterSelect/FilterSelect.jsx
> +    const [expanded, setExpanded] = useState(false);
Если переменная булева, то было бы хорошо указать это в названии. isExpanded. Так сразу понятен тип

2021-05-11 19:56 UTC, Muslik commented on src/components/FilterSelect/FilterSelect.jsx
> +            <label className={styles.caption}>{caption}</label>
label должен относиться к чему то (htmlFor), иначе он просто не нужен

2021-05-11 19:56 UTC, Muslik commented on src/components/FilterSelect/FilterSelect.jsx
> +import classNames from 'classnames/bind';
nitpick:
1. Хорошо если импорты идут в каком то порядке. (Абсолютные, относительные).

2021-05-11 19:56 UTC, Muslik commented on src/components/Table/Table.jsx
> +            <td key={order.ID+'_checkBox'} className={styles.tdCheckBox}><CheckBox/></td>
key нужно указывать только оборачивающему тегу (tr в вашем случае)

2021-05-11 19:56 UTC, Muslik commented on src/components/Table/Table.jsx
> +            <td key={order.ID+'_sum'} className={styles.td}>{(order.status === CANCELED)?'\u2014':Number(order.sum).toLocaleString('ru') + ' \u20BD'} </td>
\u2014, \u20BD
Number(order.sum).toLocaleStrung('ru')
- это все довольно сложно читается. js поддерживает unicode, вставляйте сразу символ. Вот это преобразование лучше вынести в какую то функцию и назвать ее. Тогда сразу будет понятно что тут происходит

2021-05-11 19:56 UTC, Muslik commented on src/components/Table/Table.jsx
> +    const captions = [<th key="Выбор" className={styles.th}><CheckBox/></th>, ...headerData.map(caption =>
key не нужен в одиночных элементах. И вот эти статичные поля можно сразу положить в jsx разметку

2021-05-11 19:56 UTC, Muslik commented on src/components/Table/Table.jsx
> +                <tfoot className={styles.thead}>
tfoot с классом thead )

2021-05-11 19:56 UTC, Muslik commented on src/components/Table/Table.jsx
> +                                <label className={styles.labelCount}>Выбрано записей: 0</label>
Зачем тут label если по клику на него ничего не произойдет. label нужен для input-ов

2021-05-11 19:56 UTC, Muslik commented on src/components/CheckBox/CheckBox.module.css
> +        --opacity: 1;
Есть какой то практические смысл создавать переменные для всего?

2021-05-11 19:56 UTC, Muslik commented on src/components/CheckBox/CheckBox.module.css
> +        background: var(--backgroundState, var(--background));
Что за такая комбинация переменных? Немного странно выглядит

2021-05-12 09:48 UTC, Inkvizi commented on src/components/CheckBox/CheckBox.jsx
> +                <input type="checkbox" className={styles.checkBox} id = {id}/>
Ознакомился

2021-05-12 11:27 UTC, Inkvizi commented on src/components/FilterSelect/FilterSelect.jsx
> +    const [expanded, setExpanded] = useState(false);
Указал

2021-05-12 11:33 UTC, Inkvizi commented on src/components/FilterSelect/FilterSelect.jsx
> +            <label className={styles.caption}>{caption}</label>
исправил

2021-05-12 11:34 UTC, Inkvizi commented on src/components/FilterSelect/FilterSelect.jsx
> +import classNames from 'classnames/bind';
Исправил

2021-05-12 11:37 UTC, Inkvizi commented on src/components/Table/Table.jsx
> +            <td key={order.ID+'_checkBox'} className={styles.tdCheckBox}><CheckBox/></td>
Удалил ненужное

2021-05-12 11:43 UTC, Inkvizi commented on src/components/Table/Table.jsx
> +    const captions = [<th key="Выбор" className={styles.th}><CheckBox/></th>, ...headerData.map(caption =>
это не одиночный элемент, это элемент в массиве. Если я удалю оттуда key, то получаю варнинги в браузере и eslint. Про статичные поля не понял. Весь этот код:
```
[
    <th key="Выбор" className={styles.th}>
      <CheckBox />
    </th>,
    ...headerData.map((caption) => (
      <th key={caption} className={styles.th}>
        {caption}
      </th>
    )),
  ]
```
 нужно разместить в jsx?

2021-05-12 11:44 UTC, Inkvizi commented on src/components/Table/Table.jsx
> +                <tfoot className={styles.thead}>
руки не успели за мыслью) исправил

2021-05-12 11:45 UTC, Inkvizi commented on src/components/Table/Table.jsx
> +                                <label className={styles.labelCount}>Выбрано записей: 0</label>
Заменил на div

2021-05-12 11:51 UTC, Inkvizi commented on src/components/CheckBox/CheckBox.module.css
> +        --opacity: 1;
этот код я взял при поиске решения для стилизации чекбокса. Я так понимаю, что переменные тут создаются для тех вещей, которые меняются в зависимости от каких-то условий.

2021-05-12 11:56 UTC, Inkvizi commented on src/components/CheckBox/CheckBox.module.css
> +        background: var(--backgroundState, var(--background));
возможно я неудачно подобрал название, но backgroundState предполагается задавать в стилях с определенными состояниями, а background это значение по умолчанию. Благодаря наличию backgroundState можно быстро найти места которые переопределят отображение по-умолчанию для компонента.

2021-05-12 19:43 UTC, Muslik approved these changes
Очень круто, что все таки познакомился с eslint и prettier

2021-05-14 11:36 UTC, merged